declare const styles: {
  readonly "admin": string;
  readonly "admin__footer": string;
  readonly "admin__header": string;
  readonly "admin__main": string;
  readonly "admin__nav": string;
  readonly "avatar": string;
  readonly "avatar-circle": string;
  readonly "avatar-container": string;
  readonly "btn": string;
  readonly "btn--primary": string;
  readonly "card": string;
  readonly "dashboard": string;
  readonly "dashboard__item": string;
  readonly "dashboard__item--col": string;
  readonly "dashboard__item--full": string;
  readonly "header-main": string;
  readonly "header-right": string;
  readonly "header-side": string;
  readonly "logo": string;
  readonly "main": string;
  readonly "menu": string;
  readonly "menu__item": string;
  readonly "menu__link": string;
  readonly "rect-avatar": string;
  readonly "s64": string;
  readonly "sidenav": string;
  readonly "ticker": string;
  readonly "ticker__item": string;
  readonly "toolbar": string;
};
export = styles;

